spring:
#  profiles:
#    active: "docker"
  application:
    name: job_connect
  datasource:
    url: jdbc:postgresql://localhost:5433/job_connect
    username: db_user
    password: db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  redis:
    host: localhost
    port: 6379
#    password: yourpassword
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 425875539698-rs2j9g709rqm50df6ef8nss2oj9a5a1v.apps.googleusercontent.com
config:
    aws_s3:
      region: us-east-1
      public_bucket: job-connect-public-bucket
springdoc:
  swagger-ui:
    path: /swagger-ui.html

#logging:
#  level:
#    com.job_connect: INFO