spring:
  application:
    name: job_connect
  datasource:
    url: jdbc:postgresql://localhost:5432/job_connect
    username: postgres
    password: 14022001
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0


config:
    aws_s3:
      region: us-east-1
      public_bucket: job-connect-public-bucket

#logging:
#  level:
#    com.job_connect: INFO